title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://wpfsuite.elecho.dev

aux_links:
  Source Code: https://github.com/OrgEleCho/EleCho.WpfSuite
